max:
  cpus: 62 # cores
  ram: 30 # GB
  swap_size: 30 # GB
  gpus: 8

  shm_rate: ram / swap_size if swap_size != 0 else 1
  memory: ram + swap_size

  backup_space: 200 # GB
  work_space: 500 # GB

allow_userID:
  - m11007s05
  - m11007s05-1
  - m11007s05-2

max_default_capability:
  cpus: 8
  memory: 32
  gpus: 1

  backup_space: 50
  work_space: 200

max_custom_capability:
  m11007s05:
    cpus: max
    memory: max
    gpus: max
    backup_space: max
    work_space: max

  m11007s05-1:
    cpus: max
    memory: max
    # if there is not parameter, follow by max_default_capability

  m11007s05-2:
    cpus: 12
    memory: 64
    gpus: 4
    # if there is not parameter, follow by max_default_capability
    work_space: max
